#!/usr/bin/env node
/*
 * build-shops.mjs -- Static Chaos shops & economy report.
 *
 * Parses every area's #SHOPS (keeper mob + the item types it trades + buy/sell
 * markups + open hours), links each keeper to its mob and the room it spawns
 * in (via #RESETS), and lists what each shop stocks (items given to the keeper
 * via 'G' resets).
 *
 * Emits under world-maps/:  shops.json, SHOPS.md
 * Usage:  node tools/build-shops.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseAreaFile, loadAreaList, cell, itemTypeName } from './lib/area.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AREA_DIR = path.join(ROOT, 'area');
const OUT = path.join(ROOT, 'world-maps');

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const rooms = new Map(), mobs = new Map(), objs = new Map();
  const shops = [];
  const keeperRoom = new Map();   // keeperVnum -> roomVnum (from M reset)
  const keeperStock = new Map();  // keeperVnum -> [objVnum] (from G resets to that keeper)

  const parsed = loadAreaList(AREA_DIR).map((f) => parseAreaFile(path.join(AREA_DIR, f)));
  for (const a of parsed) {
    for (const r of a.rooms) rooms.set(r.vnum, { name: r.name, area: a.id });
    for (const m of a.mobiles) mobs.set(m.vnum, { name: m.name, level: m.level, area: a.id });
    for (const o of a.objects) objs.set(o.vnum, { name: o.name, type: itemTypeName(o.itemType), cost: o.cost });
    for (const s of a.shops) shops.push({ ...s, area: a.id });
  }
  // link keepers to rooms + stock by walking resets
  for (const a of parsed) {
    let lastMob = 0;
    for (const r of a.resets) {
      if (r.command === 'M') { lastMob = r.arg1; if (!keeperRoom.has(r.arg1)) keeperRoom.set(r.arg1, r.arg3); }
      else if (r.command === 'G' && lastMob) { if (!keeperStock.has(lastMob)) keeperStock.set(lastMob, []); keeperStock.get(lastMob).push(r.arg1); }
    }
  }

  const roomStr = (v) => { const r = rooms.get(v); return r ? `${r.name} (#${v}, ${r.area})` : (v ? `#${v}` : 'unknown'); };

  // ---- json ----
  const data = {
    stats: { shops: shops.length },
    shops: shops.map((s) => ({
      keeper: s.keeper, keeperName: mobs.get(s.keeper)?.name || `#${s.keeper}`, area: s.area,
      room: keeperRoom.get(s.keeper) || null,
      buys: s.buyTypes.map(itemTypeName),
      profitBuy: s.profitBuy, profitSell: s.profitSell, hours: `${s.openHour}:00-${s.closeHour}:00`,
      stock: (keeperStock.get(s.keeper) || []).map((v) => ({ vnum: v, name: objs.get(v)?.name || `#${v}` })),
    })),
  };
  fs.writeFileSync(path.join(OUT, 'shops.json'), JSON.stringify(data, null, 2) + '\n');

  // ---- markdown ----
  const out = [];
  out.push('# Static Chaos -- Shops & Economy', '');
  out.push('> Generated by `tools/build-shops.mjs` from area `#SHOPS` + `#RESETS`. Do not edit by hand.', '');
  out.push('## At a glance', '', `**${shops.length}** shops.`, '');
  out.push('_Buy %_ is what the shop charges you (markup); _Sell %_ is what it pays for your goods. Both are percentages of base value.', '');
  out.push('| Shopkeeper | Where | Trades in | Buy % | Sell % | Hours |', '|---|---|---|---:|---:|---|');
  for (const s of shops.sort((a, b) => a.area.localeCompare(b.area) || a.keeper - b.keeper)) {
    const keeper = mobs.get(s.keeper);
    out.push(`| ${cell(keeper?.name || `#${s.keeper}`)} | ${cell(roomStr(keeperRoom.get(s.keeper)))} | ${s.buyTypes.map(itemTypeName).join(', ') || '—'} | ${s.profitBuy} | ${s.profitSell} | ${s.openHour}:00–${s.closeHour}:00 |`);
  }
  out.push('');

  // stock detail for shops that carry inventory
  const stocked = shops.filter((s) => (keeperStock.get(s.keeper) || []).length);
  if (stocked.length) {
    out.push('## Shop inventory (items stocked via resets)', '');
    for (const s of stocked.sort((a, b) => a.area.localeCompare(b.area))) {
      const keeper = mobs.get(s.keeper);
      out.push(`### ${cell(keeper?.name || `#${s.keeper}`)}  \`(${s.area})\``, '', `at ${roomStr(keeperRoom.get(s.keeper))}`, '');
      out.push('| Item | Type | Base value |', '|---|---|---:|');
      for (const v of keeperStock.get(s.keeper)) {
        const o = objs.get(v);
        out.push(`| ${cell(o?.name || `#${v}`)} | ${o?.type || '?'} | ${o?.cost ?? '?'} |`);
      }
      out.push('');
    }
  }

  fs.writeFileSync(path.join(OUT, 'SHOPS.md'), out.join('\n') + '\n');
  console.log(`shops : ${shops.length} shops`);
  console.log(`        -> world-maps/{shops.json, SHOPS.md}`);
}
main();
