#!/usr/bin/env node
/*
 * build-classes.mjs -- Static Chaos class / skill / spell reference.
 *
 * Parses class_table and skill_table out of src/const.c (the same tables the
 * server compiles in) and emits a character-build reference: each class's
 * core stats, and every skill/spell with its type, mana, lag and the level
 * each class learns it.
 *
 * Emits under world-maps/:  classes.json, CLASSES.md
 * Usage:  node tools/build-classes.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'world-maps');
const MAX_LEVEL = 20; // from merc.h; learn-levels above this mean "never"

// slice a C table initializer:  <decl> ... = { ...body... };
function tableBody(src, declRe) {
  const m = src.match(declRe);
  if (!m) return '';
  let i = src.indexOf('{', m.index);
  let depth = 0, start = i;
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) return src.slice(start + 1, i); }
  }
  return '';
}

function parseClasses(src) {
  const body = tableBody(src, /class_table\s*\[\s*MAX_CLASS\s*\]\s*=/);
  const re = /\{\s*"([^"]+)"\s*,\s*APPLY_(\w+)\s*,\s*\w+\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(TRUE|FALSE)\s*\}/g;
  const list = [];
  for (const m of body.matchAll(re)) {
    list.push({ name: m[1], prime: m[2], guild: +m[3], body: +m[4], mind: +m[5], spirit: +m[6], will: +m[7], manaUser: m[9] === 'TRUE' });
  }
  return list;
}

function parseSkills(src) {
  const body = tableBody(src, /skill_table\s*\[\s*MAX_SKILL\s*\]\s*=/);
  const re = /"([^"]+)"\s*,\s*\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}\s*,\s*([\w&]+)\s*,\s*([A-Z_]+)\s*,\s*([A-Z_]+)\s*,\s*[\w&]+\s*,\s*SLOT\(\s*(\d+)\s*\)\s*,\s*(\d+)\s*,\s*(\d+)/g;
  const list = [];
  for (const m of body.matchAll(re)) {
    const levels = [+m[2], +m[3], +m[4], +m[5], +m[6], +m[7]];
    list.push({
      name: m[1], levels,
      kind: m[8] === 'NULL' ? 'skill' : 'spell',
      target: m[9].replace(/^TAR_/, '').replace(/_/g, ' ').toLowerCase(),
      mana: +m[12], beats: +m[13],
    });
  }
  return list;
}

const lvl = (n) => (n > MAX_LEVEL ? '—' : String(n));

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const src = fs.readFileSync(path.join(SRC, 'const.c'), 'utf8');
  const classes = parseClasses(src);
  const skills = parseSkills(src);
  const names = classes.map((c) => c.name);

  fs.writeFileSync(path.join(OUT, 'classes.json'), JSON.stringify({
    stats: { classes: classes.length, skills: skills.length },
    classNames: names, classes,
    skills: skills.map((s) => ({ ...s, byClass: Object.fromEntries(names.map((n, i) => [n, s.levels[i] > MAX_LEVEL ? null : s.levels[i]])) })),
  }, null, 2) + '\n');

  const out = [];
  out.push('# Static Chaos -- Class, Skill & Spell Reference', '');
  out.push('> Generated by `tools/build-classes.mjs` from `src/const.c`. Do not edit by hand.', '');
  out.push('## Classes', '');
  out.push('| Class | Prime stat | Body | Mind | Spirit | Will | Caster | Guild room |', '|---|---|---:|---:|---:|---:|:--:|---:|');
  for (const c of classes) out.push(`| ${c.name} | ${c.prime} | ${c.body} | ${c.mind} | ${c.spirit} | ${c.will} | ${c.manaUser ? 'yes' : 'no'} | ${c.guild} |`);
  out.push('', '_Body / Mind / Spirit / Will are the per-class stat caps (what `mset`/`train` clamp to)._', '');

  const sep = `|---|---|---|---:|---:|${names.map(() => ':--:').join('|')}|`;

  const section = (title, rows) => {
    out.push(`## ${title}  (${rows.length})`, '');
    out.push(`| Name | Kind | Target | Mana | Lag | ${names.join(' | ')} |`);
    out.push(sep);
    for (const s of rows) out.push(`| ${s.name} | ${s.kind} | ${s.target} | ${s.mana} | ${s.beats} | ${s.levels.map(lvl).join(' | ')} |`);
    out.push('');
  };
  const avail = skills.filter((s) => s.levels.some((l) => l <= MAX_LEVEL) && s.name !== 'reserved');
  section('Spells', avail.filter((s) => s.kind === 'spell').sort((a, b) => a.name.localeCompare(b.name)));
  section('Skills', avail.filter((s) => s.kind === 'skill').sort((a, b) => a.name.localeCompare(b.name)));
  out.push('_A number is the level that class learns the ability; “—” means that class never gets it._', '');

  fs.writeFileSync(path.join(OUT, 'CLASSES.md'), out.join('\n') + '\n');
  console.log(`classes : ${classes.length} classes, ${skills.length} skills/spells parsed (${avail.length} learnable)`);
  console.log(`          -> world-maps/{classes.json, CLASSES.md}`);
}
main();
