#!/usr/bin/env node
/*
 * build-items.mjs -- Static Chaos equipment / item catalogue.
 *
 * Parses every area's #OBJECTS section and emits, under world-maps/:
 *   items.json   every object: type, wear, values, flags, stat affects
 *   ITEMS.md     a printable catalogue grouped by area, plus a stats summary
 *                and a "notable gear" table (items that grant stat affects).
 *
 * Usage:  node tools/build-items.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseAreaFile, loadAreaList, cell,
  itemTypeName, wearList, extraList, affectStr, itemValueStr,
} from './lib/area.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AREA_DIR = path.join(ROOT, 'area');
const OUT = path.join(ROOT, 'world-maps');

function statsCol(o) {
  const parts = [];
  const v = itemValueStr(o);
  if (v) parts.push(v);
  const aff = o.affects.map(affectStr);
  if (aff.length) parts.push(aff.join(', '));
  const flags = extraList(o.extra);
  if (flags.length) parts.push(`_${flags.join('/')}_`);
  return parts.join(' · ') || '—';
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const areas = [];
  const all = [];
  for (const f of loadAreaList(AREA_DIR)) {
    const a = parseAreaFile(path.join(AREA_DIR, f));
    if (!a.objects.length) continue;
    areas.push({ id: a.id, name: a.name, objects: a.objects });
    for (const o of a.objects) all.push({ ...o, area: a.id, areaName: a.name });
  }

  // ---- json ----
  const byType = {};
  for (const o of all) byType[itemTypeName(o.itemType)] = (byType[itemTypeName(o.itemType)] || 0) + 1;
  const data = {
    stats: { totalItems: all.length, areas: areas.length, byType },
    items: all.map((o) => ({
      vnum: o.vnum, name: o.name, area: o.area, type: itemTypeName(o.itemType),
      wear: wearList(o.wear), value: itemValueStr(o), flags: extraList(o.extra),
      affects: o.affects.map((a) => ({ stat: affectStr(a) })), weight: o.weight, cost: o.cost,
    })),
  };
  fs.writeFileSync(path.join(OUT, 'items.json'), JSON.stringify(data, null, 2) + '\n');

  // ---- markdown ----
  const out = [];
  out.push('# Static Chaos -- Equipment & Item Catalogue', '');
  out.push('> Generated by `tools/build-items.mjs` from the area files. Do not edit by hand.', '');
  out.push('## At a glance', '', `**${all.length}** items across **${areas.length}** areas.`, '');
  out.push('| Type | Count |', '|---|---:|');
  for (const [t, c] of Object.entries(byType).sort((a, b) => b[1] - a[1])) out.push(`| ${t} | ${c} |`);
  out.push('');

  // notable gear: anything wearable that grants stat affects, best first
  const notable = all.filter((o) => o.affects.length && wearList(o.wear).length)
    .map((o) => ({ o, power: o.affects.reduce((n, a) => n + Math.abs(a.mod), 0) }))
    .sort((a, b) => b.power - a.power).slice(0, 60);
  if (notable.length) {
    out.push('## Notable gear (stat-boosting wearables)', '', 'Top 60 by total stat magnitude.', '');
    out.push('| VNUM | Item | Type | Worn | Stats | Area |', '|---:|---|---|---|---|---|');
    for (const { o } of notable) {
      out.push(`| ${o.vnum} | ${cell(o.name)} | ${itemTypeName(o.itemType)} | ${wearList(o.wear).join('/') || '—'} | ${cell(o.affects.map(affectStr).join(', '))} | ${o.area} |`);
    }
    out.push('');
  }

  // full catalogue by area
  out.push('## Full catalogue by area', '');
  for (const a of areas.sort((x, y) => x.id.localeCompare(y.id))) {
    out.push(`### ${a.name}  \`(${a.id})\``, '', `${a.objects.length} items`, '');
    out.push('| VNUM | Item | Type | Worn | Stats / value / flags |', '|---:|---|---|---|---|');
    for (const o of a.objects.sort((x, y) => x.vnum - y.vnum)) {
      out.push(`| ${o.vnum} | ${cell(o.name)} | ${itemTypeName(o.itemType)} | ${wearList(o.wear).join('/') || '—'} | ${cell(statsCol(o))} |`);
    }
    out.push('');
  }
  fs.writeFileSync(path.join(OUT, 'ITEMS.md'), out.join('\n') + '\n');

  console.log(`items : ${all.length} items across ${areas.length} areas`);
  console.log(`        -> world-maps/{items.json, ITEMS.md}`);
}
main();
