#!/usr/bin/env node
/*
 * build-gearing.mjs -- Static Chaos verified gearing guide.
 *
 * Cross-references every wearable object's stat affects with the reset data
 * (where it actually drops) to produce a best-in-slot guide that ONLY lists
 * gear a player can really get. Explains what gear can and cannot do in this
 * MUD (see the prose below), then a ranked table per wear slot.
 *
 * Emits:  docs/GEARING-GUIDE.md
 * Usage:  node tools/build-gearing.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseAreaFile, loadAreaList, cell, itemTypeName,
  buildWorldIndex, resolveResets, describeSource,
} from './lib/area.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AREA_DIR = path.join(ROOT, 'area');
const OUT = path.join(ROOT, 'docs');

// APPLY locations that actually do something (verified in src/handler.c affect_modify)
const HP = 13, MANA = 12, MOVE = 14, AC = 17, HIT = 18, DAM = 19;
const SAVES = [20, 21, 22, 23, 24];

// the wear slots we present, in head-to-toe order, with display labels
const SLOTS = [
  ['wielded', 'Weapon (wield)'], ['body', 'Body'], ['head', 'Head'], ['about', 'About body (cloak)'],
  ['neck', 'Neck'], ['arms', 'Arms'], ['hands', 'Hands'], ['wrist', 'Wrist'], ['finger', 'Finger (ring)'],
  ['waist', 'Waist'], ['legs', 'Legs'], ['feet', 'Feet'], ['shield', 'Shield'], ['held', 'Held'],
];

function statBlock(o) {
  const s = {};
  for (const a of o.affects) s[a.loc] = (s[a.loc] || 0) + a.mod;
  const save = SAVES.reduce((n, k) => n + (s[k] || 0), 0);
  return {
    hp: s[HP] || 0, mana: s[MANA] || 0, move: s[MOVE] || 0,
    ac: s[AC] || 0, hit: s[HIT] || 0, dam: s[DAM] || 0, save,
  };
}
// general usefulness (AC/save are better when negative, so negate them)
const benefit = (b, o) => b.hp + (-b.ac) * 2 + (b.hit + b.dam) * 5 + (-b.save) * 3 + b.mana * 0.25 + b.move * 0.1
  + (o.itemType === 5 && o.values[1] && o.values[2] ? o.values[1] * (o.values[2] + 1) / 2 : 0);
// caster lean: mana + survivability + spell-save, melee accuracy ignored
const casterBenefit = (b) => b.hp + (-b.ac) * 2 + (-b.save) * 5 + b.mana * 0.6;

function statStr(o, b) {
  const p = [];
  if (o.itemType === 5 && o.values[1] && o.values[2]) p.push(`${o.values[1]}d${o.values[2]} dmg`);
  if (b.hp) p.push(`${b.hp > 0 ? '+' : ''}${b.hp} hp`);
  if (b.mana) p.push(`${b.mana > 0 ? '+' : ''}${b.mana} mana`);
  if (b.move) p.push(`${b.move > 0 ? '+' : ''}${b.move} move`);
  if (b.ac) p.push(`${b.ac} AC`);
  if (b.hit) p.push(`${b.hit > 0 ? '+' : ''}${b.hit} hit`);
  if (b.dam) p.push(`${b.dam > 0 ? '+' : ''}${b.dam} dam`);
  if (b.save) p.push(`${b.save} save`);
  return p.join(', ') || '—';
}
// level of the toughest mob guarding an item (for the difficulty column)
function guardLevel(o, idx, itemSources) {
  let lvl = 0;
  for (const s of itemSources.get(o.vnum) || []) {
    const m = s.mob && idx.mobs.get(s.mob);
    if (m && m.level > lvl) lvl = m.level;
  }
  return lvl;
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const parsed = [];
  for (const f of loadAreaList(AREA_DIR)) parsed.push(parseAreaFile(path.join(AREA_DIR, f)));
  const idx = buildWorldIndex(parsed);
  const { itemSources } = resolveResets(parsed);

  // every obtainable wearable that grants a working affect
  const wearables = [];
  for (const a of parsed) for (const o of a.objects) {
    if (!itemSources.has(o.vnum)) continue;            // not placed -> unobtainable
    if (!o.affects.length && o.itemType !== 5) continue;
    const b = statBlock(o);
    wearables.push({ o, b, area: a.id });
  }

  const out = [];
  out.push('# Static Chaos — Verified Gearing Guide', '');
  out.push('> Generated by `tools/build-gearing.mjs` from the area files + reset data. Every item below is **actually obtainable** (something places it in the world). Do not edit by hand — re-run the tool.', '');

  // ---- how gear works ----
  out.push('## How gear works here (read this first)', '');
  out.push('In Static Chaos, **gear only changes seven things**: max **HP**, max **mana**, max **move**, **AC**, **hitroll**, **damroll**, and **saving throws**. That is the complete list (verified in `src/handler.c` `affect_modify`).', '');
  out.push('Gear **cannot** raise your class power — `body / mind / spirit / will`, your `powers[]` (school ranks, aegis, ki, forms…), or `primal`. Those come **only from training** (rage, discipline, research, forming). Item bonuses to **STR/DEX/INT/WIS/CON are disabled in code and do nothing** — ignore "+10 Str" on an item, it is a no-op.', '');
  out.push('So there is **no class-specific armour** — everyone competes for the same pieces. What differs is *which stats your class cares about*:', '');
  out.push('| Class | Wants | Ignores |', '|---|---|---|');
  out.push('| **Sorcerer / Patryn** (casters) | HP, AC, **save-vs-spell**, **mana** (Concentrate / rune fuel) | hitroll, damroll (chants & runes don\'t use them) |');
  out.push('| **Saiyan** | HP, AC, hitroll, damroll (melee Ryuken), saves | mana (ki uses its own pool) |');
  out.push('| **Fist** | HP, AC, hitroll, damroll (combos), saves | mana |');
  out.push('| **Mazoku** | HP, AC, saves — **but cannot wear material gear** unless trained in **M_HUMAN**; otherwise needs **astral** items | — |');
  out.push('', 'Saving throws matter in PvP: a low (negative) **save-vs-spell** is the main defence against a Sorcerer\'s chants.', '');

  // ---- finding gear ----
  out.push('## Finding gear in-game', '');
  out.push('- **`ofind <kw>`** lists item **vnums** in `[brackets]` — that is the *item\'s* id, **not a room**. `goto` takes a *room* vnum, which is why `goto 30` fails (30 was the sword\'s id).', '');
  out.push('- **`owhere <kw>`** shows where loaded copies currently are (room / who carries them) — only works if a copy is loaded right now.', '');
  out.push('- For the full "where does X drop" map, see `world-maps/SPAWNS.md` and `world-maps/ITEMS.md` (the **Found** column).', '');

  // ---- best in slot ----
  out.push('## Best in slot (obtainable only)', '');
  out.push('Ranked by general usefulness. **Get from** shows the toughest source; **L** is that mob\'s level (difficulty). Casters: prefer the mana / save rows even if they rank lower. AC and save are better the more negative.', '');
  for (const [slot, label] of SLOTS) {
    // skip flag-spam items wearable in >4 slots -- those are junk/buggy, not real BIS
    const inSlot = wearables.filter((w) => w.o.wear && wearListHas(w.o.wear, slot) && slotCount(w.o.wear) <= 4);
    if (!inSlot.length) continue;
    const top = [...inSlot].sort((x, y) => benefit(y.b, y.o) - benefit(x.b, x.o)).slice(0, 4);
    const shown = new Set(top.map((t) => t.o.vnum));
    // surface the best caster-leaning pick only if it's genuinely different and not already shown
    const casterPick = [...inSlot].sort((x, y) => casterBenefit(y.b) - casterBenefit(x.b))[0];
    out.push(`### ${label}`, '', '| VNUM | Item | Stats | L | Get from |', '|---:|---|---|---:|---|');
    for (const { o, b } of top) {
      const src = (itemSources.get(o.vnum) || [])[0];
      out.push(`| ${o.vnum} | ${cell(o.name)} | ${cell(statStr(o, b))} | ${guardLevel(o, idx, itemSources) || '—'} | ${cell(src ? describeSource(src, idx, itemSources) : '?')} |`);
    }
    if (casterPick && !shown.has(casterPick.o.vnum) && (casterPick.b.mana > 0 || casterPick.b.save < 0)) {
      out.push(`| ${casterPick.o.vnum} | ${cell(casterPick.o.name)} _(caster)_ | ${cell(statStr(casterPick.o, casterPick.b))} | ${guardLevel(casterPick.o, idx, itemSources) || '—'} | ${cell(describeSource((itemSources.get(casterPick.o.vnum) || [])[0], idx, itemSources))} |`);
    }
    out.push('');
  }

  // ---- phantoms ----
  out.push('## Phantom items (look powerful, can\'t be obtained)', '');
  out.push('These exist as item templates and show up in `ofind`, but **no reset places them**, so they never enter the world in normal play. Don\'t chase them:', '');
  out.push('| VNUM | Item | Stats | Area |', '|---:|---|---|---|');
  const phantoms = [];
  for (const a of parsed) for (const o of a.objects) {
    if (itemSources.has(o.vnum)) continue;
    if (!o.affects.length && !(o.itemType === 5 && o.values[1])) continue;
    const b = statBlock(o);
    const big = b.hp >= 100 || b.mana >= 100 || (b.hit + b.dam) >= 15 || (o.itemType === 5 && o.values[1] * o.values[2] >= 60);
    if (big) phantoms.push({ o, b, area: a.id });
  }
  phantoms.sort((x, y) => benefit(y.b, y.o) - benefit(x.b, x.o));
  for (const { o, b, area } of phantoms.slice(0, 20)) {
    out.push(`| ${o.vnum} | ${cell(o.name)} | ${cell(statStr(o, b))} | ${area} |`);
  }
  out.push('');

  fs.writeFileSync(path.join(OUT, 'GEARING-GUIDE.md'), out.join('\n') + '\n');
  console.log(`gearing : ${wearables.length} obtainable wearables, ${phantoms.length} notable phantoms`);
  console.log(`          -> docs/GEARING-GUIDE.md`);
}

// wear-flag bit test by slot name (mirrors lib WEAR_BITS without importing it)
const SLOT_BIT = {
  finger: 2, neck: 4, body: 8, head: 16, legs: 32, feet: 64, hands: 128,
  arms: 256, shield: 512, about: 1024, waist: 2048, wrist: 4096, wielded: 8192, held: 16384,
};
function wearListHas(wear, slot) { return (wear & SLOT_BIT[slot]) !== 0; }
function slotCount(wear) { return Object.values(SLOT_BIT).filter((bit) => wear & bit).length; }

main();
