#!/usr/bin/env node
/*
 * build-spawns.mjs -- Static Chaos spawn & loot cross-reference.
 *
 * Walks every area's #RESETS (the loader's placement script) to answer
 * "where do I find X?" -- which rooms each creature spawns in, and where
 * each item comes from (floor / carried / equipped / in a container).
 * Also emits a level-banded hunting guide over the reachable world.
 *
 * Emits under world-maps/:  spawns.json, SPAWNS.md
 * Usage:  node tools/build-spawns.mjs   (run build:world first for reachability)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseAreaFile, loadAreaList, cell, itemTypeName,
  buildWorldIndex, resolveResets, describeSource,
} from './lib/area.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AREA_DIR = path.join(ROOT, 'area');
const OUT = path.join(ROOT, 'world-maps');
const band = (l) => (l >= 90 ? '90+' : l >= 70 ? '70–89' : l >= 50 ? '50–69' : l >= 30 ? '30–49' : l >= 10 ? '10–29' : '1–9');

function main() {
  fs.mkdirSync(OUT, { recursive: true });

  const parsed = [];
  for (const f of loadAreaList(AREA_DIR)) parsed.push(parseAreaFile(path.join(AREA_DIR, f)));

  // shared global indexes + correct reset resolution (fixes P/container sourcing)
  const idx = buildWorldIndex(parsed);
  const { mobs, rooms, objs } = idx;
  const { mobSpawns, itemSources: itemSrc } = resolveResets(parsed);

  // reachability: which areas are reachable from recall (from world.json if present)
  let unreachable = new Set();
  try {
    const w = JSON.parse(fs.readFileSync(path.join(OUT, 'world.json'), 'utf8'));
    unreachable = new Set(w.reports.unreachableAreas);
  } catch { /* world.json not built yet -- treat all as reachable */ }

  const srcStr = (s) => describeSource(s, idx, itemSrc);

  // ---- json ----
  const data = {
    stats: { mobsPlaced: mobSpawns.size, itemsPlaced: itemSrc.size },
    mobSpawns: Object.fromEntries([...mobSpawns].map(([v, set]) => [v, { name: mobs.get(v)?.name || `#${v}`, level: mobs.get(v)?.level ?? null, rooms: [...set] }])),
    itemSources: Object.fromEntries([...itemSrc].map(([v, list]) => [v, { name: objs.get(v)?.name || `#${v}`, type: itemTypeName(objs.get(v)?.itemType), sources: list }])),
  };
  fs.writeFileSync(path.join(OUT, 'spawns.json'), JSON.stringify(data, null, 2) + '\n');

  // ---- markdown ----
  const out = [];
  out.push('# Static Chaos -- Spawn & Loot Cross-Reference', '');
  out.push('> Generated by `tools/build-spawns.mjs` from area `#RESETS`. Do not edit by hand.', '');
  out.push('## At a glance', '', `**${mobSpawns.size}** creatures and **${itemSrc.size}** items are placed by resets.`, '');

  // hunting guide (reachable mobs only)
  out.push('## Hunting guide (by level band)', '');
  out.push('Reachable creatures only, grouped by level. _Lvl_ is the mob level; pick targets near your own.', '');
  const reachableMobs = [...mobSpawns].map(([v, set]) => ({ v, set, m: mobs.get(v) })).filter((x) => x.m && !unreachable.has(x.m.area));
  for (const b of ['1–9', '10–29', '30–49', '50–69', '70–89', '90+']) {
    const inBand = reachableMobs.filter((x) => band(x.m.level) === b).sort((a, z) => a.m.level - z.m.level || a.m.name.localeCompare(z.m.name));
    if (!inBand.length) continue;
    out.push(`### Level ${b}  (${inBand.length})`, '', '| Lvl | Creature | Found in | Area |', '|---:|---|---|---|');
    for (const x of inBand) {
      const where = [...x.set].slice(0, 3).map((rv) => { const r = rooms.get(rv); return r ? `${r.name} (#${rv})` : `#${rv}`; }).join('; ');
      out.push(`| ${x.m.level} | ${cell(x.m.name)} | ${cell(where)}${x.set.size > 3 ? ` +${x.set.size - 3}` : ''} | ${x.m.area} |`);
    }
    out.push('');
  }

  // where to find each creature (all, by area)
  out.push('## Where each creature spawns', '');
  const byAreaMobs = {};
  for (const [v, set] of mobSpawns) { const m = mobs.get(v); const area = m?.area || '?'; (byAreaMobs[area] ??= []).push({ v, set, m }); }
  for (const area of Object.keys(byAreaMobs).sort()) {
    out.push(`### \`${area}\`${unreachable.has(area) ? ' ⚠️ (not reachable on foot)' : ''}`, '', '| Creature | Lvl | Spawns in |', '|---|---:|---|');
    for (const { v, set, m } of byAreaMobs[area].sort((a, z) => (z.m?.level || 0) - (a.m?.level || 0))) {
      const where = [...set].map((rv) => { const r = rooms.get(rv); return r ? `${cell(r.name)} (#${rv})` : `#${rv}`; }).join('; ');
      out.push(`| ${cell(m?.name || `#${v}`)} | ${m?.level ?? '?'} | ${where} |`);
    }
    out.push('');
  }

  // where to find each item (by item's home area)
  out.push('## Where each item comes from', '');
  const byAreaItems = {};
  for (const [v, list] of itemSrc) { const o = objs.get(v); const area = o?.area || '?'; (byAreaItems[area] ??= []).push({ v, list, o }); }
  for (const area of Object.keys(byAreaItems).sort()) {
    out.push(`### \`${area}\``, '', '| Item | Type | Source(s) |', '|---|---|---|');
    for (const { v, list, o } of byAreaItems[area].sort((a, z) => a.v - z.v)) {
      out.push(`| ${cell(o?.name || `#${v}`)} | ${itemTypeName(o?.itemType)} | ${cell(list.map(srcStr).join('; '))} |`);
    }
    out.push('');
  }

  fs.writeFileSync(path.join(OUT, 'SPAWNS.md'), out.join('\n') + '\n');
  console.log(`spawns : ${mobSpawns.size} mobs placed, ${itemSrc.size} items placed`);
  console.log(`         -> world-maps/{spawns.json, SPAWNS.md}`);
}
main();
